//DELETE http://localhost:8080/api/bookings/3

//GET http://localhost:8080/users

//GET http://localhost:8080/api/bookings?page=0&size=5

//GET http://localhost:8080/api/bookings/user/2?page=0&size=2

PUT http://localhost:8080/api/bookings/2
Content-Type: application/json
currentUserId: 2

{
  "status": "CONFIRMED"
}
